map:
    startSize: 2000
    endSize: 10
    startResizeEpisodeNumber: 3
    timeFromStartSizeToEndSizeSeconds: 1800
moles:
    timer: 1
    moles_per_team: 1
    number_team_moles: 1
    
doDaylightCycle: "false"
episodes:
    time: 20
scoreboard: Taupe Gun INSA